<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

genesis_structural_wrap( 'site-inner', 'close' );
genesis_markup(
	[
		'close'   => '</div>',
		'context' => 'site-inner',
	]
);

/**
 * Fires immediately after the site inner closing markup, before `genesis_footer` action hook.
 *
 * @since 1.0.0
 */
do_action( 'genesis_before_footer' );

/**
 * Fires to display the main footer content.
 *
 * @since 1.0.1
 */
do_action( 'genesis_footer' );

/**
 * Fires immediately after the `genesis_footer` action hook, before the site container closing markup.
 *
 * @since 1.0.0
 */
do_action( 'genesis_after_footer' );

genesis_markup(
	[
		'close'   => '</div>',
		'context' => 'site-container',
	]
);

/**
 * Fires immediately before wp_footer(), after the site container closing markup.
 *
 * @since 1.0.0
 */
do_action( 'genesis_after' );
wp_footer(); // We need this for plugins. ?>

<script type="text/javascript">
var currentdate1 = new Date(); 
    var datetime1 = "Now Time: " + currentdate1.getDate() + "/"
                + (currentdate1.getMonth()+1)  + "/" 
                + currentdate1.getFullYear() + " @ "  
                + currentdate1.getHours() + ":"  
                + currentdate1.getMinutes() + ":" 
                + currentdate1.getSeconds();
console.log(datetime1);
jQuery(window).load(function () {
	var a_links = jQuery('#wdm-oam-faq-questions .vc_tta-panel-heading a');
	jQuery.each( a_links, function( i, val ) {
		var this_hash = jQuery(this).attr('href').split('#');
	 	jQuery(this).attr('href', '#'+this_hash[1]);
	});
});
/*jQuery(document).ready(function(){
	setTimeout(function() {
		var a_links = jQuery('#wdm-oam-faq-questions .vc_tta-panel-heading a');
		jQuery.each( a_links, function( i, val ) {
			var this_hash = jQuery(this).attr('href').split('#');
		 	jQuery(this).attr('href', '#'+this_hash[1]);
		});
	}, 2000);
});*/
</script>
<?php genesis_markup(
	[
		'close'   => '</body>',
		'context' => 'body',
	]
);

?>
</html>
